### ISSUE TITLE
What's the difference between "getItemViewType" and "getPrototypeIndex" in RendererBuilder

### ISSUE THREAD

**Issue by fibers** [pedrovgs/Renderers#16]
So what's the difference between "getItemViewType" and "getPrototypeIndex" in RendererBuilder..

You find the matched renderer class in getItemViewType, but loops prototypes again in getPrototypeIndex to get the index.. it really make me confused.

**Comment by pedrovgs** [comment]
There is no difference. That method was added to add readability to the code. If you take a look to the implementation of ``getPrototypeIndex`` you'll see how this method delegates the execution to ``getItemViewType``:

```java

  /**
   * Returns the index of the prototype index using the content.
   *
   * @param content used to get the prototype index.
   * @return the prototype index.
   */
  private int getPrototypeIndex(T content) {
    return getItemViewType(content);
  }

```

In the context where this private method is used it's easy to understand the code if you read this method:

```java

/**
   * Create a Renderer getting a copy from the prototypes collection.
   *
   * @param content to render.
   * @param parent used to inflate the view.
   * @return a new renderer.
   */
  private Renderer createRenderer(T content, ViewGroup parent) {
    int prototypeIndex = getPrototypeIndex(content);
    Renderer renderer = getPrototypeByIndex(prototypeIndex).copy();
    renderer.onCreate(content, layoutInflater, parent);
    return renderer;
  }

```

Given a content instance passed as argument you have to get a copy of the renderer prototype. To me, it's easier to understand if you find a prototype by the prototype index and not the view type, because the view type could be related to the prototype index or not (in this library it is). I understand this can be difficult to understand :).

Is this the answer to your question?
