### ISSUE TITLE
Some permissions are added to APK

### ISSUE THREAD

**Issue by alorma** [pedrovgs/Renderers#17]
I detected this behaviour just after add your library.

```
android:uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from AndroidManifest.xml:2:1 reason: com.pedrogomez.renderers has a targetSdkVersion < 4
android:uses-permission#android.permission.READ_EXTERNAL_STORAGE
IMPLIED from AndroidManifest.xml:2:1 reason: com.pedrogomez.renderers requested WRITE_EXTERNAL_STORAGE
```

**Comment by pedrovgs** [comment]
Hi @alorma!

I've published a snapshot version with a tentative fix. I've detected this issue is not directly related with the library itself, it's related with how the final application manifest is merged using the manifests added from the libraries you are using. Adding a min sdk and a target sdk this problem should be fixed.

Can you check if the version 2.0.4-SNAPSHOT is working as should? I'll publish a new release with this change if this is the one we need.

Thanks for the issue!

Here you have another similar issue opened in other repository: https://github.com/commonsguy/cwac-merge/issues/16
