### ISSUE TITLE
Add support for PagedListAdapter

### ISSUE THREAD

**Issue by pedrovgs** [pedrovgs/Renderers#45]
After the latest Architecture Components release made by Google during December 2017 we've noticed they have released a new adapter named ``PagedListAdapter`` we should support. As the architecture component is a new module we should provide this as a new renderers module so we don't add the architecture components to the main artifact. More information can be found in [this video](https://www.youtube.com/watch?v=4VGmFztUF6g&feature=youtu.be)

**Comment by emmano** [comment]
I have an early implementation of a `PagedRendererAdapter` [here](https://github.com/emmano/Renderers/commits/paging).

The `DataSource` implementation I have is not working as it should since it does not load pages on demand, but at least it is displaying content. I may need to add `Room`to show a proper example (probably not a bad idea since that is what most people will use). Also, I still need to add support for `getItem()` returning null since the Paging library supports placeholders; it returns `null` for an item that has not loaded yet.

There are a bunch of refactor opportunities in most `RendererAdapters` at first glance. Their `onBindViewHolder()` and `onCreateViewHolder()` are quite similar.

This branch should also close #44 

You (and or @Serchinastico) are still welcome to take a look.

**Comment by emmano** [comment]
#47 should close this

**Comment by pedrovgs** [comment]
PR #47 already reviewed @emmano. Thank you so much for your time and effort contributing to this repository.
